"""
src/state.py
Extended GraphState for AgriAgent vision pipeline.
Builds on SmartDesk's existing state.
"""
from enum import Enum
import operator
from typing import Annotated, Any, Dict, List, Literal, Optional, TypedDict
from pydantic import BaseModel, Field
from PIL import Image
from langchain_core.messages import AnyMessage
from langgraph.graph.message import add_messages


def merge_dicts(a: dict, b: dict) -> dict:
    c = a.copy()
    c.update(b)
    return c


# ── Artifact Type Enum ─────────────────────────────────────────────────────────
class ArtifactType(str, Enum):
    # SmartDesk Standard Types
    RAW_CONTEXT = "raw_context"        # File contents read from disk
    SUMMARY = "summary"                # Summarized output
    ANSWER = "answer"                  # Direct answer to a question
    ACTION_ITEMS = "action_items"      # Extracted action items
    SEARCH_RESULTS = "search_results"  # RAG / search results
    STATUS = "status"                  # Status / confirmation message
    # AgriAgent Vision Types
    VISION_MASK = "vision_mask"        # 2D NumPy binary mask
    SPRAY_MAP = "spray_map"            # GPS-tagged selective spray contours
    ANALYSIS_REPORT = "analysis_report"# Herbicide savings % & agronomy metrics


class Artifact(BaseModel):
    id: str
    type: ArtifactType
    title: str
    description: str
    metadata: Dict[str, Any] = Field(default_factory=dict)
    payload: Any = None


class Task(BaseModel):
    id: str = Field(..., description="Unique task ID generated by Python.")
    agent: str
    instruction: str
    context_artifacts: List[str] = Field(default_factory=list)
    expected_output: str
    status: str = "pending"


class Box(TypedDict):
    x1: float
    y1: float
    x2: float
    y2: float
    label: str
    score: float


class Mask(TypedDict):
    mask_array: Any        # NumPy binary array
    predicted_iou: float
    box: Box               # Source bounding box
    label: str


class GraphState(TypedDict):
    # === SmartDesk Existing Fields ===
    messages: List[AnyMessage]
    current_task: Optional[Dict]
    completed_tasks: List[Dict]
    artifacts: Dict[str, Any]

    # === SmartDesk Agent Histories ===
    workspace_messages: List[AnyMessage]
    knowledge_messages: List[AnyMessage]
    productivity_messages: List[AnyMessage]

    # === AgriAgent Vision Extensions ===
    image: Optional[Image.Image]            # Input field image
    image_path: Optional[str]               # Path to uploaded image
    text_prompt: Optional[str]              # Natural language command
    boxes: List[Box]                        # Grounding DINO outputs
    masks: List[Mask]                       # SAM 2 outputs
    refinement_count: int                   # Refinement iterations (max 2)
    spray_map: Optional[Dict]               # GPS-tagged spray coordinates
    analysis_report: Optional[Dict]         # Per-app metrics
    application_id: Optional[int]           # Which of 5 apps is active

    # === Evaluation Fields ===
    ground_truth_masks: Optional[List]      # For IoU/Dice computation
    evaluation_metrics: Optional[Dict]      # Computed metrics
